### ISSUE TITLE
Support for Transmission ?

### ISSUE THREAD

**Issue by MrBretze** [Tympanix/Electorrent#10]
Look at the title :)

**Comment by Tympanix** [comment]
rTorrent is next. After that I will be glad to look at Transmission. Thank you :)

**Comment by MrBretze** [comment]
Thanks for that :)

**Comment by Tympanix** [comment]
You will have to thank @Paaff for this wonderful implementation 👍

**Comment by Paaff** [comment]
If you encounter any bugs or think of helpful additions, you're more than welcome to open new Issues :)!
