### ISSUE TITLE
Torrent info?

### ISSUE THREAD

**Issue by dvvdv** [tympanix/Electorrent#103]
I'd like to see torrent info while downloading!
Just the basic stuff:
-Status
-Activity 
-Trackers
-Peers
-Files
You could maybe implement it like this:
https://i.imgur.com/SY4BY10.png
I'm sure y'all will think of something!

**Comment by tympanix** [comment]
This has been discussed in multiple issues primarily #77 and #25. Since the program is meant as a utility tool, not a fully fledged bit torrent application, the feature has not been of the highest priority. It is a great feature none the less. Thanks for reporting.

**Comment by tympanix** [comment]
Trumped by #25
