### ISSUE TITLE
AbstractTorrent Decodename fails if the torrent is all numbers

### ISSUE THREAD

**Issue by cdloh** [tympanix/Electorrent#116]
**Client:**
- [x] rTorrent

**Client Version:**
 0.9.6

**Application Version:**
2.3.0

**Description:**

If a torrent is all numbers it comes in [here](https://github.com/tympanix/Electorrent/blob/master/src/scripts/bittorrent/rtorrent/rtorrentservice.js#L86) as an int. Then when abstracttorrent attempts to [decode the name](https://github.com/tympanix/Electorrent/blob/master/src/scripts/bittorrent/abstracttorrent.js#L10) it fails as .replace doesn't exist on ints

**Comment by tympanix** [comment]
Very nice debugging work. Thank you. Fix will come later today

**Comment by tympanix** [comment]
Fixed in https://github.com/tympanix/node-rtorrent/commit/52e697b443798d72b2a9b2404e59917e4ebd3c32
