### ISSUE TITLE
Support multiple connections?

### ISSUE THREAD

**Issue by dsully** [tympanix/Electorrent#123]
Is there any way to connect to / select from multiple backend servers?

If not, consider this a feature request. :)

**Comment by tympanix** [comment]
Yes. There is support for multiple server configurations. You can add a new connection by pressing `Ctrl+N`. You can also quick switch between your servers using `Ctrl+1`, `Ctrl+2`... and so on. Have a look in the menu bar (files, edit ect.) to explore more options.
