### ISSUE TITLE
seedbox.io strangely not supported

### ISSUE THREAD

**Issue by Charkel** [tympanix/Electorrent#125]
I am very happy with Seedbox.io and they uses rTorrent but they said that currently their setup is not supported by Electorrent even thought they first thought it would be no problems and that their users had used it in the past.

They really tried giving me all the support they could think of like setting my RCP path "/RPC/24344/" and other stuff. (great guys) But it just keeps spinning and spinning and never connects. (no problems on my end with firewall or anything)

Ultimately after having a engineer doing some hands on test they came to the conclusion that

> "Im afraid that this program appears to not support our setup, it does not properly load the configured RPC link so im afraid that it will not work :("

I know it's their setup and that they could fix it somehow i guess. But **maybe something could be done from the developing end so that more configs would work. Like theirs for example**

**Comment by tympanix** [comment]
This may be because their setup uses digest authentication while Electorrent only supports basic authentication. Similar to #90 and #97. Adding digest authentication is a planned feature. If you can confirm that Seedbox.io in fact uses digest authentication, please get back to me. Then we have a definite solution.

**Comment by Charkel** [comment]
Thank you I will contact them right away

**Comment by Charkel** [comment]
> This may be because their setup uses digest authentication while Electorrent only supports basic authentication. Similar to #90 and #97. Adding digest authentication is a planned feature. If you can confirm that Seedbox.io in fact uses digest authentication, please get back to me. Then we have a definite solution.

You were right my friend. Here is the confirmation from seedbox.io.
Hope you can implement it that would be awesome! :)

> Hi,
That would indeed be the culprit - Once he gets that resolved you should be all set :)
Best regards,
Daniel Walker
Hostingor LTD

**Comment by tympanix** [comment]
I will see if I can find some time to implement this feature, busy times at the moment though.

**Comment by ButchPooch** [comment]
Has it been fixed? I can't manage to setup it with seedbox.io and I found this thread, but on recent thread I have read that digest authentication is now supported.

**Comment by tympanix** [comment]
I don't use seedbox.io hence I can't test it. Digest authentication has been implemented, which should provide the features necessary to support this. In Electorrent, I would try to fiddle with the path option. Once you find that path where the XML-RPC is available, it should work. Sometimes this path is `/RPC2`. Also try to find the path to `action.php` (if you have ruTorrent web UI) and point to that one.

**Comment by ForgottenWolf** [comment]
Not sure if this has already been answered elsewhere but to anyone who stumbles upon this, `rutorrent/plugins/httprpc/action.php` is the path you want. Can confirm seedbox.io works with the client.

**Comment by littlepeon** [comment]
hey am trying to connect to seedbox.io with Electorrent...
so what port do i put,    and what do i put in the RCP path space... for transdrone i put /RPC/<user>/
have trid the rutorrent/plugins/httprpc/action.php and it did not work
