### ISSUE TITLE
Download link for MacOs malfunctioning 

### ISSUE THREAD

**Issue by thomasfaller** [tympanix/Electorrent#127]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [ ] rTorrent

**Client Version:**

**Operating System:**
-MacOs

**Application Version:**

**Description:**

When clicking on the download link for MacOs, I get the following message from Heroku:

<img width="1120" alt="screenshot 2018-08-27 15 31 22" src="https://user-images.githubusercontent.com/23104176/44665699-7ab8de00-aa0e-11e8-9ea6-262e4ba89a7d.png">

**Comment by tympanix** [comment]
Yes. That is because it is running on a free dyno which has run out of monthly hours. I will see what I can do about that. Use the [release page](https://github.com/tympanix/Electorrent/releases) instead for now.

**Comment by tympanix** [comment]
Heroku dyno has been updated.
