### ISSUE TITLE
Unable to connect to rTorrent server

### ISSUE THREAD

**Issue by PBXg33k** [tympanix/Electorrent#129]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [x] rTorrent

**Client Version:**
rTorrent git-master (using linuxserver's docker image)

**Operating System:**
Windows

**Application Version:**
2.4.0

**Description:**
Unable to connect to rTorrent server. Connection establishes, but immediatly loses connection with following error in console.

```
angular.js:14199 Error: Error: XML-RPC fault: Method 'd.multicall' not defined
    at rtorrentservice.js:92
    at processQueue (angular.js:16696)
    at angular.js:16712
    at Scope.$eval (angular.js:17994)
    at Scope.$digest (angular.js:17808)
    at angular.js:18033
    at completeOutstandingRequest (angular.js:6045)
    at angular.js:6324
```

After checking the available XML-RPC commands on my rTorrent server i see that there is a `d.multicall2` method but not a `d.multicall` method

**Comment by tympanix** [comment]
Thank you for the insight. This is unfortunate but seems to be a change from rTorrent `9.7.0` and onward. I will have to make the xmlrpc library version agnostic to support this. Should be manageable as long as I can find some form of documentation on the new `d.multicall2` function call.

**Comment by Xaero252** [comment]
Indeed. 
There's a bit of information on the change at the top of this page:
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html
In the "Important" note box. It seems the main change is that now all functions require a target.

https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#d-commands
Has the documentation on d.multicall2 with examples provided. I'm not super familiar or I'd just take a stab at it myself.

**Comment by tympanix** [comment]
@lucasdcrk I would love to find the time to achieve this fix. Unfortunately there are other things on my plate for the time being.

**Comment by lucasdcrk** [comment]
Okay np

**Comment by tympanix** [comment]
I managed to quick-fix this in a couple of hours (see https://github.com/tympanix/node-rtorrent/commit/4614a3dede22c98f0fe758904e1e60c96737403c). Support for older version of rtorrent will be dropped. Release will follow.

**Comment by Xaero252** [comment]
Awesome! Thanks for the update!
Looking forward to the new release.
