### ISSUE TITLE
Windows 32-bit binaries

### ISSUE THREAD

**Issue by mivalsten** [tympanix/Electorrent#131]
**Operating System:**
Windows 10
**Application Version:**
2.4.0
**Description:**
Hi, could you compile this application for windows 32-bit as well? I have intel atom based tablet which does not support 64-bit OS and would really like to use your application this there.

**Comment by tympanix** [comment]
See #91. A 32 bit version of the application will not be able to receive automatic updates, as well as having other issues. If you really want a 32 bit version you may have luck building one yourself. I am sorry for this inconvenience.

**Comment by mivalsten** [comment]
Ok, leaving this for another people that might want to compile electorrent for themselves on 32-bit architecture. Below commands are working, but are probably absolutely not the best or even good approach to the task. If anyone wants to use them, feel free to do with it whatever you want.

Command are in **powershell runing with admin privilages**, and are using chocolatey windows package manager
```
#where you want electorrent source code to be downloaded
$electorrentRepoLocation = "D:\Electorrent"

#install chocolatey
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

install dependencies
choco upgrade -y nodejs.install yarn python2 git

#install more dependencies, 
npm install --global --production windows-build-tools

#this is almost surely not needed, but I had it installed
#choco upgrade -y vcbuildtools -ia "/Full"

#clone electorrent to location you specified earlier. Using cmd /C because git is not being recognised in shell without restarting shell
cmd /C "git clone https://github.com/tympanix/Electorrent.git $electorrentRepoLocation"

cd $electorrentRepoLocation

#people from internet told me to do this
yarn

#was unable to buid it with electron-builder, but electron-packager worked. Not the best solution, can't self-update and is not an installer, but, again, it's working
yarn add electron-packager

node_modules/.bin/electron-packager ./ --platform=win32 --arch=ia32
```

**Comment by tympanix** [comment]
Glad you got it to work. If you switch to NSIS then using `electron-builder` should work. That is why we need to migrate Electorrent to NSIS before we can have official 32 bit support. Sadly this means reconstructing the whole auto-update infrastructure around Electorrent.

**Comment by mivalsten** [comment]
Could you hint at how can I switch to NSIS?

**Comment by tympanix** [comment]
You find the documentation on NSIS [here](https://www.electron.build/configuration/nsis). The build configuration you need to change is located here: https://github.com/tympanix/Electorrent/blob/73b2553fb1db22bbadfe36c58bdd626aae135f35/package.json#L63

Cheers!

**Comment by mivalsten** [comment]
Well, yup, got it working fine. Thank you!

Updated script, still powershell admin:

```
#where you want electorrent source code to be downloaded
$electorrentRepoLocation = "D:\Electorrent"

#install chocolatey
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

#install dependencies
choco upgrade -y nodejs.install yarn python2 git

#install more dependencies, 
npm install --global --production windows-build-tools

#this is almost surely not needed, but I had it installed
#choco upgrade -y vcbuildtools -ia "/Full"

#clone electorrent to location you specified earlier. Using cmd /C because git is not being recognised in shell without restarting shell
cmd /C "git clone https://github.com/tympanix/Electorrent.git $electorrentRepoLocation"

cd $electorrentRepoLocation

#people from internet told me to do this
yarn

#was unable to buid it with electron-builder, but electron-packager worked. Not the best solution, can't self-update and is not an installer, but, again, it's working
yarn add electron-builder

#change squirrel to NSIS as per Tympanix's suggestion
(Get-Content .\package.json).replace('"target": "squirrel"', '"target": "NSIS"') | Set-Content .\package.json

node_modules/.bin/electron-builder --ia32
```
