### ISSUE TITLE
Electorrent no longer connects to qBittorrent via HTTPS

### ISSUE THREAD

**Issue by aTosser** [tympanix/Electorrent#138]
**Client:**
- [ ] µTorrent
- [X] qBittorrent
- [ ] Transmission
- [ ] rTorrent

**Client Version:**
4.1.4,4.1.5
**Operating System:**
Gentoo Linux
**Application Version:**
2.5.1
**Description:**
After upgrading to 2.5.1 electorrent no longer connects to qBittorrent 4.1.4.
I read the update notes and the 2 issues related to qBittorrent and the API changes so I upgraded to 4.1.5 and electorrent still gives the error. The connection could not be established.

**Comment by aTosser** [comment]
The issue lies in HTTPS. If I disable https in qBittorrent and reconfigure in Electorrent everything is fine. Something in the new release broke HTTPS.

**Comment by KmtqaxCX** [comment]
Can confirm the issue also with the qbitorrent version 3.3.7 on debian stretch.

Is there a way to disable automatic updates of electorrent in the windows installation version ?

**Comment by tympanix** [comment]
That is very unfortunate. I will work towards fixing this issue ASAP. Sadly, no you can't disable automatic updates. I will make a separate issue for that.

**Comment by KmtqaxCX** [comment]
Thanks for the update,but Im still experiencing the issue ... Maybe @tympanix can confirm ?

**Comment by tympanix** [comment]
I had a working setup with qBittorrent 4.1.5 and a self-signed certificate. Can you describe the issue you are seeing @KmtqaxCX and/or error messages?

**Comment by KmtqaxCX** [comment]
sorry,wanted to write to @aTosser :P 
I have a debian stretch,QBT 3.3.7 daemon installed with a self-signed certificate for https
after the 2.5.1 update and even after the 2.5.2 update im receiving the following error : The connection could not be established.
When i downgrade to 2.3.1 it works fine
HTTP works also fine.

**Comment by tympanix** [comment]
Very glad you got it to work 👍. It may seem that older versions of Electorrent did not care if certificates were expired. I will make sure to add a notification for expired certificates in the future to be more informative of this scenario.

**Comment by aTosser** [comment]
2.5.2 linux appimage did not fix this issue for me. I am still not able to use HTTPS configuration with Electorrent/qBittorrent

**Comment by tympanix** [comment]
Very odd. Are you able to view the stack trace in the developer console? That would certainly help.

**Comment by aTosser** [comment]
Settings Error Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049)
    at TLSSocket.emit (events.js:182)
    at TLSSocket._finishInit (_tls_wrap.js:631)

**Comment by aTosser** [comment]
I tried to add a new server and configure again with the same issue. This issue did not begin until >2.5.0. Whatever changes were introduced into HTTPS handling since then is where the problem must be. This identical configuration was used until the update.

**Comment by tympanix** [comment]
The 2.5.0 update facilitates an all new implementation of qBittorrent using nodejs which is more stable, reliable and secure. Therefore there is not a single change I can revert to fix this issue easily. I am afraid there is going to be a small process. If you are ok with this I believe we can fix this issue. Something also tells me what you are experiencing is a one-off type of error for your specific setup.

I have done some local testing and nodejs does not seem to have any problems with letsEncrypt certificates whatsoever. Does Electorrent ask you to trust/verify the certificate (with a popup modal) right after logging in or does it complain with `unable to verify the first certificate` straight away?

**Comment by aTosser** [comment]
The error I posted is the only error that shows in the console log. Every time the application attemtps to connect to the qB client or the connect button is pressed another instance of that error is generated in the log.

**Comment by aTosser** [comment]
I have found the solution. Node.js has it's own baked in list of certificate authorities and does not include some of the more popular public CAs. (Let's Encrypt) The solution is to use the contents of fullchain.pem rather than just cert.pem This should probably be wiki'd.

**Comment by tympanix** [comment]
I was investigating exactly this. Great finding! I will make sure to wiki this solution

**Comment by parkerlreed** [comment]
Is this still an issue? It let me trust the self signed cert but cannot use it as it says the common name doesnt match.... Of course it wont its self signed

![image](https://github.com/user-attachments/assets/31a78b80-c547-4b1a-bc62-511f4768d67c)

**Comment by parkerlreed** [comment]
I tried generating new keys with both the CN set to the IP or DNS name, but qBittorrent won't load at all on the new ones :/
