### ISSUE TITLE
qBittorrent on path not working

### ISSUE THREAD

**Issue by devster31** [tympanix/Electorrent#151]
**Client:**
- [ ] µTorrent
- [x] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:** 4.1.5

**Operating System:** MacOS 10.12.6

**Application Version:** 2.6.0.325

**Description:**
Using the full domain name `example.com` over `https` with `443` as port and `/qbt/` as path (exactly as I do on a browser) fails to connect to the running qBittorrent instance.

**Comment by SSoft7** [comment]
I have this same issue. I have noticed that for the following URL

> http://domain-name.com/qbittorrent/{custompath}/

Electorrrent sends following request to the server

> http://domain-name.com/qbittorrent/login    (it is stripping the last component of the path i.e {custompath}/.)

So, The correct request uri should be 

> http://domain-name.com/qbittorrent/{custompath}/login

I hope you can add a fix soon 👍   @tympanix

**Comment by tympanix** [comment]
Thank you for investigating this @SSoft7. It would seem this is just a small pesky bug. Hopefully I can fix this soon
