### ISSUE TITLE
qBittorrent-git (4.2.0alpha) Login failure

### ISSUE THREAD

**Issue by aTosser** [tympanix/Electorrent#159]
I am testing out qbittorrent-git and they have changed the API again. I get login failures now in electorrent. I can still log in fine at the webUI so.
Just a heads up.

`Settings Error Error: Invalid login`
`   at QBittorrent.<anonymous> (/tmp/.mount_electojW…torrent/index.js:93)`
`   at Request._callback (/tmp/.mount_electojW…torrent/index.js:68)`
`    at Request.self.callback (/tmp/.mount_electojW…uest/request.js:185)` 
`    at Request.emit (events.js:182)`
`    at Request.<anonymous> (/tmp/.mount_electojW…est/request.js:1161)`
`    at Request.emit (events.js:182)`
`    at IncomingMessage.<anonymous> (/tmp/.mount_electojW…est/request.js:1083)`
`    at Object.onceWrapper (events.js:273)`
`    at IncomingMessage.emit (events.js:187)`
`    at endReadableNT (_stream_readable.js:1092)`

**Comment by tympanix** [comment]
Thank you for informing about this. I looks like we have to update qbittorent yet again. Keeping backwards compatibility will be harder and harder though. For now use an older version of qbittorrent

**Comment by aTosser** [comment]
@tympanix Heads up it seems (according to the github milestones for qbittorrent) that they are planning to relese 4.2.0 in the next week-ish... May be time to take a poke at this.

The `/api/v2/` prefix that you are aware of is becoming the default and the legacy API is going to be dropped from 4.2.0+ the login method has been moved to `/api/v2/auth/login` this why logins no longer work properly. 

It also seems some methods have been changed some, I noticed while browsing the code `deletePerm` no longer exists and `deleteFiles` is now a parameter passed to `delete` so there may be a couple of hiccups along the way.

Let me know if you need some testing, we can sit down and hammer it out if you have the time.

Weeeeeee....

**Comment by olympia** [comment]
More and more repos and channels are providing qBittorrent v4.2.0 now and due to the above, Electorrent is not usable as from this version. Could you please look at the upgrade?

**Comment by tympanix** [comment]
An upgrade is surely necessary. Sadly, I don't have the resources to implement this feature as of right now. 😢 This will however be my top priority when I can allocate time for this project.

**Comment by AnanyaKirti** [comment]
could you tell me what needs to be done? Maybe I can help

**Comment by tympanix** [comment]
@AnanyaKirti we need an updated implementation of [node-qbittorrent](https://github.com/tympanix/node-qbittorrent) which is a dependency of Electorrent. Backwards compatibility with older versions would be desirable.

**Comment by icex** [comment]
@tympanix - see my quick patch https://github.com/icex/node-qbittorrent/commit/83eab5184be72e8c5eb690d780b15fcaa2b25b03

No backward compatibility, all I could do in a few hours(I have zero experience in Angular and Electron, sorry).

**Comment by aTosser** [comment]
honestly with icex's patch we could just rename node-qbittorrent to node-legacy-qbittorrent and either make a new menu entry or some conditional voodoo for auto-detection.

**Comment by roncamma** [comment]
Woawh pretty cool !:) :heart_decoration:
