### ISSUE TITLE
Adding existing labels to torrents adds a new label. Spaces replaced with "+"

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#16]
Steps:
Add/upload torrent > click on the label icon at the top > choose desired label

Instead of assigning the chosen label to that torrent, it adds a new label with the same label name except that the spaces are replaced with plus '+' signs. For example, I have a label with "Study References". The new label is now "Study+References"

**Comment by Tympanix** [comment]
This should be fixed. Which bittorrent client are we talking about?

**Comment by valdotdev** [comment]
Oh sorry I forgot. It's qBittorrent v3.3.6
