### ISSUE TITLE
Can't connect to Qbittorrent 4.2.1(Windows) from Ubuntu 18.04 using electorrent

### ISSUE THREAD

**Issue by persson1589** [tympanix/Electorrent#161]
**Client:**
- [ ] µTorrent
- [x ] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**
Qbittorrent 4.2.1(Windows)
**Operating System:**
Windows 10
**Application Version:**
Electorrent 2.6.1 appImage
**Description:**
Can't connect to Qbittorrent 4.2.1(Windows) from Ubuntu 18.04 using electorrent but using a web browser on the Ubuntu computer it works

**Comment by persson1589** [comment]
I would like to add I use a different port for qbitorrent web ui than usual, I use the port 1200. Maybe that's an issue?

**Comment by persson1589** [comment]
I would like to add I use a different port for qbitorrent web ui than usual, I use the port 1200. Maybe that's an issue?

**Comment by tympanix** [comment]
Qbittorrent 4.2.x is not supported yet, see #159. Once support is added this should resolve itself
