### ISSUE TITLE
Failing to connect to qbtorrent

### ISSUE THREAD

**Issue by blakie21737** [tympanix/Electorrent#162]
**Client:**
- [ ] µTorrent
- [X ] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**
qBittorrent v4.2.1 Web UI (64-bit)

**Operating System:**
Mac OS 10.15.3 (19D76)

**Application Version:**
Version 2.6.1 (2.6.1.331)

**Description:**
First of all.. Great program!!! I've used this for some time on windows and its been fantastic and reliable!

My issue is with setting up the server, i have confirmed everything is working perfectly with the web UI its behind nginx and secured with lets encrypt on a noip dns domain. i put in the domain, protocol, user, pass and client program and it thinks for a while but fails to connect, when i try with port 443 it also fails i tried mucking with the path variable to no success also even though its running on the root domain. i have tried using a local address and it spits the error that the certificate doesn't match the host address, I'm at a loss somethings going on but i cant figure it out?

**Comment by tympanix** [comment]
Support for qBittorrent 4.2.x is still missing, see #159
