### ISSUE TITLE
Cannot connect to rTorrent seedbox using either /xmlrpc or /RPC2

### ISSUE THREAD

**Issue by jackitsdotcom** [tympanix/Electorrent#164]
**Client:**
[x ] rTorrent
**Client Version:**
Electorrent 2.6.1
**Operating System:**
Windows 10 x64 Version 1903 Build 18362.535
**Application Version:**
rtorrent 0.9.8 / libtorrent 0.13.6
**Description:**
I use Whatbox for a seedbox provider. They say I can access rTorrent via the following:

> RPC Endpoint (Cookies) | https://[removed for privacy].whatbox.ca/RPC2
> RPC Endpoint (HTTP Auth) | https://[removed for privacy].whatbox.ca/xmlrpc

I have tried connecting to both endpoints, with either `/xmlrpc` or `/RPC2` in the Path box. `/xmlrpc` takes nine seconds to fail, `/RPC2` takes two seconds to fail. Both have the error "Connection problem - the connection could not be established"

I'm sorry but I can't work out where the logs for Electorrent are available. If someone could point me to the location I'd be happy to post them. I'm also not sure where I can see logs on the rTorrent side if they're relevant. 

Thankyou for your help.

**Comment by jackitsdotcom** [comment]
Issue no longer occuring.

**Comment by tympanix** [comment]
Sorry for my late reply. Glad you fixed it though. Can you describe the solution for future reference?
