### ISSUE TITLE
Version 2.7.0 Does not launch from the AppImage.

### ISSUE THREAD

**Issue by aTosser** [tympanix/Electorrent#172]
```
$ electorrent
[4165:0328/202336.713374:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was
found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You
need to make sure that /tmp/.mount_electoMaipv7/chrome-sandbox is owned by root and has mode
4755.
Trace/breakpoint trap
```

**Comment by aTosser** [comment]
This is just a packaging issue for systems that do not have kernel unprivleged namespace support. The helper is not required for those systems that have this kernel feature enabled. However there are linux systems that may not have a kernel new enough or simply do not have the option enabled in distribution.

**Comment by tympanix** [comment]
I've been reading up on solutions for this problem. It would be very nice if you can test out the solution, once 2.7.1 is up 👍
