### ISSUE TITLE
Can't connect to Deluge

### ISSUE THREAD

**Issue by Lyechee** [tympanix/Electorrent#173]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [*] Deluge

**Client Version:**
Deluge 1.3.15 on Ubuntu 18.04

**Operating System:**
Windows 10

**Application Version:**
Up to date

**Description:**
I can't find how to add my Deluge server as a new server. 

- The IP is the right one
- I tried http and https
- can't find any username in the deluge configuration, tried "localhost", blank, the user of ubuntu
- tried the default password deluge, and the session one
- port : 8112 as shown in the deluge parameters

It keeps saying "Connection could not be established". Of course I can reach the webui...

Thanks for your help

**Comment by Lyechee** [comment]
Turns out it can connect to the daemon webui but not the "regular" deluge webui. Is there a workaround ?

**Comment by tympanix** [comment]
I don't know the exact difference between the two - maybe you can enlighten me. I believe Deluge was implemented following the official API, although it was testing using the GUI version of Deluge.

**Comment by Lyechee** [comment]
Actually, I have nothing to teach you ! I am a newbie in the unix world so the difference between deluge and deluge daemon.... 
All I know is that it didn't work with deluge only installed with GUI, and it started to work after installing the daemon version also. I think I will have to start from scratch because I'm afraid it could lead to conflicts.
