### ISSUE TITLE
peer list/file list/more info of a torrent?

### ISSUE THREAD

**Issue by riaqn** [tympanix/Electorrent#175]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [x] rTorrent
- [ ] Transmission
- [ ] Deluge

**Client Version:**
0.9.8

**Operating System:**
Linux 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux

**Application Version:**
2.6.1

**Description:**
I'm not sure if I'm using it right - is there no place to look at the peer list, the file list and more detailed info of a torrent? Is it just a rtorrent thing or in general?

**Comment by tympanix** [comment]
This is in general. Focus has been on supporting multiple clients instead of complete support for a single one. This means that the basic functionality for each client is in place (viewing, adding, deleing torrents). Advanced functionality, as you describe, has not been implemented yet.

**Comment by riaqn** [comment]
Hi @tympanix  thanks for the reply. Do you plan to support it in the near future? It's a great project with great potential.

**Comment by tympanix** [comment]
Not in the near future, but certainly sometime. We still have some work to do maintain and update existing clients. Problem is, if we start implementing this advanced functionality, we have to support it for all clients, which makes the implementation a bit more substantial.

**Comment by riaqn** [comment]
That's reasonable. Keep up the good work!
