### ISSUE TITLE
Slow download from herokuapp

### ISSUE THREAD

**Issue by karibuTW** [tympanix/Electorrent#178]
Hello guys,
I'm downloading the windows app from Vietnam, and it's extremely slow, 80kb/s at best, while I have optic fiber (200m)
I've tested it on a server based in US, and it went fast (20mb/s).
I've tested it on another server based in Vietnam and it was as slow.

It could obviously come from the network in Vietnam, but I'm able to download fast others file located on different infra.

I am the only one? How is others countries in Asia? And do you need mirrors? (Happy to help, I own mirror.freedif.org)

**Comment by tympanix** [comment]
To my knowledge, Heroku does not discriminate traffic by country. My downloads from Heroku are adequate. The Heroku app is simply serving files from github. If you try to download from [the releases page](https://github.com/tympanix/Electorrent/releases) does that change anything?

**Comment by karibuTW** [comment]
Hi, I guess it's more related to bandwidth of the country or the route taken.
This morning, it's much better, 5mb/s

I thought it was on a different host than Github. Little to do then.

I guess we can close this then.

Thank you
