### ISSUE TITLE
Status bar with general information (total up/down etc.)

### ISSUE THREAD

**Issue by karibuTW** [tympanix/Electorrent#179]
Hello,
First of all, very well done with Electorrent. It works well and smooth.

Is there a way to show the total Down and Up? We can only see by torrent, but no sum. It's useful to see if we have reached the maximum bandwidth we have, etc..

Thank you

PS: I have another feature request as well to see the available disk space, as some torrent clients might run out of space.

PS2: It would be great as well to rename the Servers. At the moment having Transmission @ IP is a bit difficult as I have 6 Transmission clients in different locations.

PS3: Any plan for a web based solution? That would be awesome!

**Comment by tympanix** [comment]
General information likes this could certainly be useful. Do you have a particular client in mind? We can support this feature for clients which exposes an API point with this data. If the client API does not provide such information, there is not much Electorrent can do.

Maybe Electorrent should support a status bar at the bottom of the window for clients that supports this feature.

**Comment by tympanix** [comment]
Let me address some of the other topics.

You can already rename servers if you go into *settings* and *servers* (it's the blue icon with the "tag" on it).

As for web support I don't think this will be a feature. Electorrent depends on a lot of OS specific features which would not be applicable in a web browser. We would have to have a clearly defined boundary between what is supported in the web version and what is supported in an Electron/NodeJS based app. Although there is much of the codebase which can be shared, separating the two is a hard and time consuming job taking the code structure of Electorrent into account.

**Comment by karibuTW** [comment]
Thanks for the answer.
I'm using Transmission and Rtorrent mostly. Not sure they exposed such info
But a status bar will be great indeed! (Up/Down, may be available disk space, etc..)
Like Deluge or others torrents client status bar.

Is there a way to help?

And well noted for the others answers.
