### ISSUE TITLE
Support tTorrent android app

### ISSUE THREAD

**Issue by SonnySonnySonny** [tympanix/Electorrent#180]
If tTorrent (android app) could also be supported that will be great.

**Comment by SonnySonnySonny** [comment]
would this ever be possible? :(

**Comment by tympanix** [comment]
I don't quite get the reason for this. Electorrent is used to connect to remote servers running some kind of torrent program. If that server is your Android phone, I don't see the need to connect remotely to it. Am I missing something? Please elaborate.

**Comment by tympanix** [comment]
IMHO supporting mobile phone apps is out of scope of this project. If you have a specific proposal for this implementation. feel free to comment.

**Comment by SonnySonnySonny** [comment]
I have an android tv box that i use as a torrent server which ttorrent is installed on. I can currently add torrents remotely (remote app Transdrone) using my mobile phone but being able to add them using my Mac was the idea.
