### ISSUE TITLE
Install instructions for linux

### ISSUE THREAD

**Issue by physicalit** [tympanix/Electorrent#185]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [ x] rTorrent
- [ ] Deluge

**Client Version:**

**Operating System:**

**Application Version:**

**Description:**
For download, there is a yml file adn if i run the following in the repo i get an error: 
user@Electorrent(master) $ /usr/lib/electron6/electron ./
Error launching app
Unable to find Electron app at /home/smihuleac/Downloads/Electorrent

Cannot find module '/home/smihuleac/Downloads/Electorrent/app/app.js'. Please verify that the package.json has a valid "main" entry

Is this app functional?

**Comment by tympanix** [comment]
This app is functional on linux. I've not run the app directly with the "electron" executable for a long time. However, if this is going to work, you need to run electron from the `app` folder after doing `npm install` and `gulp build`. I can't guarantee there will be no problems though.

If you want the app for linux you best bet i to just grab the release file from the releases page here on github or compile it yourself. You can compile yourself with `npm run dist`. It requires `electron-builder`.
