### ISSUE TITLE
'All' and 'Downloading' filters are the same

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#19]
Related: #13 

So basically the _Downloading_ filter is displaying all torrents (active or not) like with the new _All_ filter.

OSX 10.11.6
qBit Win v3.3.6
Electorrent Mac v1.2.1

**EDIT:**
@Tympanix So it essentially behaves like qBittorent, which is actually what I don't like.
Any way to actually filter only the Downloading torrents? As far as I can see this isn't a bug (my bad). I'll close this for now.

**Comment by Tympanix** [comment]
I know there is still confusion on this matter concerning qBittorrent. This is why i haven't closed #13 yet. Version 1.2.1 primarily attended issues marked with _bug_. Your other suggestions will have to wait as rTorrent and Transmission is in the making for version 1.3.0. But don't worry - I will get to them eventually :+1:

**Comment by valdotdev** [comment]
> This is why i haven't closed #13 yet

Thanks for clarifying! 👍 

> Your other suggestions will have to wait as rTorrent and Transmission is in the making for version 1.3.0

No rush. Take your time! :smile:
