### ISSUE TITLE
Queue column doesn't handle zero-based numbering (transmission client)

### ISSUE THREAD

**Issue by 13k** [tympanix/Electorrent#193]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [x] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:** 3.00 (bb6b5a062e)

**Operating System:** Windows

**Application Version:** 2.7.1

**Description:**

Looks like the queue implementation doesn't account for zero-based numbering, either when sorting or displaying values.

The transmission RPC protocol specification states that the [queue position value starts at zero](https://github.com/transmission/transmission/blob/61d221c8bb5f360b0cc763da28f873410f48595f/extras/rpc-spec.txt#L126).

### Sorting

The [sorting implementation](https://github.com/tympanix/Electorrent/blob/b08dbee78b8c9e62393550020645e1826577364c/src/scripts/services/column.js#L32-L36) seems to always push the zero value queue position to last.

_(Side note on the function naming: I thought the natural numbers set included zero?)_

Manual sorting test in node console:

```
> function sorter(a, b){
... if (a < 1) return 1
...         if (b < 1) return -1
...         return a - b
...     }
undefined
> arr=[1,5,8,0,6,4,9,3]
[
  1, 5, 8, 0,
  6, 4, 9, 3
]
> arr.sort(sorter)
[
  1, 3, 4, 5,
  6, 8, 9, 0
]
```

### Display

The queue column's [render template](https://github.com/tympanix/Electorrent/blob/b08dbee78b8c9e62393550020645e1826577364c/src/scripts/bittorrent/abstracttorrent.js#L298) seems to ignore the zero value, probably because javascript treats zero as a false-y value, falling back to `torrentQueue` and it seems this scope var is undefined.

### Screenshot

Below is the queue column in the Electorrent app. The purple arrow indicates a torrent that has a position `0` in the queue. 

![20201027-181926-firefox](https://user-images.githubusercontent.com/4762/97346313-0ede9400-186a-11eb-9783-0b4997bed65d.png)

This one is from [tremotesf2](https://github.com/equeim/tremotesf2) app. The purple arrow indicates the same torrent. 

![20201027-185741-tremotesf](https://user-images.githubusercontent.com/4762/97348731-54509080-186d-11eb-8c51-95488670eb64.png)

**Comment by tympanix** [comment]
Excellent documentation on this bug. Sorry I didn't get to fix this sooner.

**Comment by 13k** [comment]
👍
