### ISSUE TITLE
Connection/authentication problems with Transmission

### ISSUE THREAD

**Issue by coaperator** [tympanix/Electorrent#196]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [x] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**
3.00 latest
**Operating System:**
win x64
**Application Version:**
2.7.1 latest
**Description:**
![image](https://user-images.githubusercontent.com/6645911/100231272-d77e0880-2f37-11eb-954f-166cafb29b9e.png)

I'm trying to connect to the transmission in the router via the network
how to fix?

**Comment by tympanix** [comment]
This is most likely due to the fact that Transmission 3 changes the API. We will have to update the Electorrent implementation for this to work.

**Comment by glowspider** [comment]
Same problem with Transmission: 2.94

Doesn't establish a connection. Transmission Remote GUI connects without problems.

![2020-11-29 17_48_58-Electorrent](https://user-images.githubusercontent.com/12909450/100546731-981f2700-326b-11eb-992e-8779a0ac30af.jpg)

**Comment by tympanix** [comment]
You are right. I tested this with newest Transmission (using linuxserver/transmission docker) without problems. That doesn't explain your scenario though. Can you double check port number, hostname/ip, username, password.

Can you debug this is any way - developer console?

**Comment by glowspider** [comment]
> You are right. I tested this with newest Transmission (using linuxserver/transmission docker) without problems. That doesn't explain your scenario though. Can you double check port number, hostname/ip, username, password.
> 
> Can you debug this is any way - developer console?

I describe the situation in detail.

Transmission 2.94 is installed on a Zyxel router.
I am currently connecting via Transmission Remote GUI 5.18.0.
I wanted to try Electorrent, downloaded the Windows version (Windows 10, 64).

Connection to Transmission Remote GUI:
![2020-11-30 09_50_03-Application options](https://user-images.githubusercontent.com/12909450/100582266-a748b800-32f1-11eb-8322-b4e0b1a98a7d.jpg)

Electorrent connection:
![2020-11-30 09_51_20-Electorrent](https://user-images.githubusercontent.com/12909450/100582323-c1829600-32f1-11eb-864b-b54cd94986e6.jpg)

I'm not a programmer, so I don't even know what a developer console is, I'm afraid I won't be able to help. Sorry. I just inform you that I could not connect.

**Comment by coaperator** [comment]
> You are right. I tested this with newest Transmission (using linuxserver/transmission docker) without problems. That doesn't explain your scenario though. Can you double check port number, hostname/ip, username, password.
> 
> Can you debug this is any way - developer console?

![image](https://user-images.githubusercontent.com/6645911/101378991-cda7be00-38c4-11eb-8e1d-691e12c3cbcb.png)

**Comment by coaperator** [comment]
In the config, for some reason, the address is / gui instead of / transmission / rpc

**Comment by tympanix** [comment]
Thanks for debugging @coaperator. You mention `/gui` but I don't see that in your screenshot. Can you elaborate what you mean?

**Comment by coaperator** [comment]
> Thanks for debugging @coaperator. You mention `/gui` but I don't see that in your screenshot. Can you elaborate what you mean?
not at all )

I managed with great difficulty, by workarounds, to go into the settings management, after adding the settings of the first connection
during the first setup I specified /transmission /rpc
but after that if you open the settings, then we are in the **path** field - /gui is written, and updating this setting does not help fix the problem
![image](https://user-images.githubusercontent.com/6645911/101536652-56992500-39ab-11eb-9e42-5768c5dd773e.png)

**Comment by tympanix** [comment]
The issue with `/gui` is odd but actually due to the fact that you have µTorrent selected in your screenshot and not Transmission.

I've been able to solve the problem by looking at your previous screenshot of the developer console 🥳

**Comment by coaperator** [comment]
> The issue with `/gui` is odd but actually due to the fact that you have µTorrent selected in your screenshot and not Transmission.
> 
> I've been able to solve the problem by looking at your previous screenshot of the developer console 🥳

Transmission also has /gui

![image](https://user-images.githubusercontent.com/6645911/101985098-e6362080-3c96-11eb-997e-45a1cec2109d.png)

**Comment by tympanix** [comment]
I am currently working on a new release which will include a couple of fixes. You'll see the commit linked in this thread when published
