### ISSUE TITLE
[Feature] Linux support ?

### ISSUE THREAD

**Issue by MrBretze** [Tympanix/Electorrent#2]
Look the title :)

**Comment by Tympanix** [comment]
Thank you for the suggestion.

I will take a quick look tomorrow for compiling for linux. Alternatively you are more than welcome to clone the repo and compile a version for yourself :)

**Comment by Tympanix** [comment]
I have added a .deb package for linux/debian in the newest [1.0.1  release](https://github.com/Tympanix/Electorrent/releases/tag/v1.0.1)
