### ISSUE TITLE
Message or notification saying the connection was lost with the remote host

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#20]
There are times when I didn't realize my home server was down and I'm using Electorrent to remotely monitor my downloads. Since the application doesn't alert me that the host was down or the connection was lost, I only noticed when the speed indicators stopped refreshing. So a simple message/message pop-up, preferably with native notifications support, would be helpful.

Relative to this, I think it's a good idea to bring back the _Reload_ option whenever the host is back up and running, Unless of course the app will reload itself once it detects the host again and establishes connection.

**Comment by Tympanix** [comment]
Lots of good improvements. I'll get to them once support for rTorrent is done. Keep them coming :+1:

**Comment by Tympanix** [comment]
Will be available in the new version v1.3.0 coming out soon!
