### ISSUE TITLE
Electorrent for iOS

### ISSUE THREAD

**Issue by AlexR00T** [tympanix/Electorrent#202]
**Client:**
- [ ] µTorrent
- [x] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Description:**

Hello.. is there gonna be an iOS app?

**Comment by tympanix** [comment]
That is too big of an implementation since all the NodeJS related code would not run a mobile device. While I enjoy your proposal it would be a project in and of itself.

**Comment by AlexR00T** [comment]
What about using ionicframework for mobile devices?? If needed help i have some spare time i can use to get into ionic and make it but ill have to first learn a bit how your electorrent works and implement your code into ionic. Are you interested?

**Comment by tympanix** [comment]
Certainly. If you want to bootstrap the project that's fine with me. I still have work to do maintaining Electorrent (the codebase is becoming quite dated). ReactNative, Flutter or Ionic seems to be good choices nowadays. Let me know if you manage to get something up and running :+1:

**Comment by tympanix** [comment]
Actually you might also want to check out: https://play.google.com/store/apps/details?id=org.transdroid.lite&hl=en&gl=US
