### ISSUE TITLE
[FEATURE] a cli.

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [tympanix/Electorrent#269]
**multi cli**
Why is there no simple cli to get data from most torrent clients? rtorrent isn't a cli. it's a fuckinounagu tui
please save me

**Description:**
bundle a cli
`electorrent info <hash or query [lucky search]> --server <server>`returns progress, size, etc, option --json flag.
`electorrent search <query>  --server <server>` searches current torrents
`electorrent all  --server <server name>` lists all torrents
etc, just whatever you come up with.

offer an api, and make another project to call that api if you'd rather... an api would be a bonus for the community to make stuff mostly though.

**Comment by tympanix** [comment]
I like your idea!

However, I have to limit the scope of what to implement and this sound like a niche feature for technical people.
