### ISSUE TITLE
Progress percentage not showing correctly

### ISSUE THREAD

**Issue by shareiff** [Tympanix/Electorrent#27]
Progress percentage in the progress bar is displaying {{label()}} on MacOS client version 1.3.0.125

**Comment by Tympanix** [comment]
Thank you for reporting. I will need a bit more information from you to fix this though. What is the bittorrent client and version? (e.g. uTorrent, qBittorrent, rTorrent ect.)

**Comment by shareiff** [comment]
uTorrent 2.2.1 (build 25302) on Windows

**Comment by Tympanix** [comment]
Turns out it was an inconsistency of the uTorrent WebAPI. Travis and AppVeyor are building - hang tight! I would however recommend updating uTorrent though. If you find any more bugs let me know 👍

**Comment by shareiff** [comment]
Thanks for the quick resolution. You'll have to pry 2.2.1 from my cold,dead hands :)
