### ISSUE TITLE
uTorrent 2.2.1 doesn't show date added

### ISSUE THREAD

**Issue by shareiff** [Tympanix/Electorrent#28]
Shows "invalid date" instead.
![screen shot 2016-12-02 at 9 43 53 pm](https://cloud.githubusercontent.com/assets/7517913/20857175/aa6ff044-b8d8-11e6-9059-bb1ea4611082.png)

**Comment by Tympanix** [comment]
This is still a result of the web API being immature in version 2.2.1. The web API simply doesn't provide this information. Another git repo also suffers from this and simply [avoids fetching that information](https://github.com/onegambler/uTorrent-Web-API-Wrapper/blob/914a7336b1d83e57f97d2eb3d21145ade42e8bc1/src/main/java/com/utorrent/webapiwrapper/core/MessageParser.java#L114). Maybe an option to remove the column all together would be an option.

I also don't think the official web ui manages to resolve this problem (if it's even compatible). Let me know if you have information in regards to this.

**Comment by Tympanix** [comment]
Closing. This is inherently not fixable.
