### ISSUE TITLE
Cant's connect to Synology Download Station after updating Electorent to 2.8.0

### ISSUE THREAD

**Issue by enchained** [tympanix/Electorrent#293]
**Client:**
Synology Download Station

**Client Version:**
3.8.15-3563

**Operating System:**
Windows 10

**Application Version:**
2.8.0

**Description:**
It worked fine right before the update, but after it just gives the connection error. Downgrading to 2.7.3 fixes the issue.

JS console logs:
```
settings.ts:158 Settings Error TypeError: Cannot read property 'isSuccess' of undefined
    at synologyservice.ts:174
    at async SynologyClient.connect (synologyservice.ts:171)
```

**Comment by tympanix** [comment]
Sadly, I knew this was a risk with the v2.8.0 release due to the fact that I have no way of testing the Synology implementation. I have contacted Synology for a developer instance of their Download Station weeks ago which would allow me to test. No response yet.

One option would be to implement a mocked version of the API to test against. Otherwise we need a contributor with both a Synology product and programming knowledge to implement/fix the issue.

**Comment by enchained** [comment]
@tympanix Could it be just JS local/global scopes issue? 
If I put a devtools breakpoint at synologyservice.ts:174, JS console tells me that `this.isSuccess` is undefined, while `self.isSuccess` is defined at that point (and it is used like that later at the 194 line). I can't edit main.js right there to test my theory (the app crashes if I do), but I probably can try extracting and repacking the app.asar later (I have no experience in proper electron development/testing, so this is what came to mind).

**Comment by tympanix** [comment]
I have applied a possible fix to the master branch. If you would like to validate the fix you may clone the repository, run `npm install` and then `npm start` to start the application. However, there may be more issues to solve (since I can't do testing on my own)

**Comment by tympanix** [comment]
Any updates on this using newest release? I have currently no possible way to test this

**Comment by enchained** [comment]
Hi. Sorry, didn't have the time to setup the dev environment earlier.

Thanks to your fixes, previous error was gone, but a new appeared. Currently on 2.8.2, it gives me this error:
```
Uncaught (in promise) TypeError: Cannot read property 'size_downloaded' of undefined
    at new SynologyTorrent (synologytorrent.ts:12)
```

If I edit main.js from asar (and repack it back) so that

```
// Information variables.
var detail = data.additional.detail;
var trans = data.additional.transfer;
var track = data.additional.tracker;
```

are above the

```
super({
    hash: data.id,
    name: data.title,
    size: data.size,
    percent: (trans.size_downloaded / data.size) * 1000,
```

it can receive the task list and does not give any console errors (I tested viewing the task list, adding URL, removing torrent, browsing by status, sorting, resaving connection settings,  restarting).

The only thing that bothers me is that the new speed status bar shows 0 B/s (9327.5 GB/s) 0 B/s (12811.2 GB/s). It correctly shows DL speed when something is downloading, but those speeds in brackets (are they supposed to be max speeds per session?) are way off.

Today I cloned the master branch and did npm install and npm start, but for some reason, getting tasks this way gives me the error code 105 - "The logged in session does not have permission.", even though the task and auth requests are exactly the same in both cases. Looks like something is wrong with syno session when I start via npm, so I'll have to use the other debug method until I figure this out.

**Comment by tympanix** [comment]
@enchained thank you for your efforts 👍 

I will apply the fixes you provided to the master branch and also look at the status bar (I think it is supposed to show the total downloaded and uploaded data, but not sure).

The 105 http error sounds strange - it should be the same either way. If you find time somehow, it would be nice if you would validate the master branch.
