### ISSUE TITLE
Self-update/auto-update fails with uncaught exception

### ISSUE THREAD

**Issue by sensibleish** [tympanix/Electorrent#303]
When attempting to use auto-update in 2.8.0 and in the previous version, upon clicking `Quit and Install` I get this error:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: shell.openltem is not a function at /Users/----/Applications/Electorrent.app/Contents/Resources/app.asar/lib/update.js:69:19 at FSReqCallback.oncomplete (fs.js:171:23)
```

![Screen Shot 2022-10-10 at 2 57 37 PM](https://user-images.githubusercontent.com/1753270/194958896-15fa4ce7-8963-4246-86a5-b54fccc25829.png)

<img width="728" alt="Screen Shot 2022-10-10 at 2 57 27 PM" src="https://user-images.githubusercontent.com/1753270/194958775-f0706fcb-ef96-4771-8745-9a3537e98329.png">

MacOS 12.6. Running as a non-admin user. Application is installed in `~/Applications`, not `/Applications`.

**Comment by tympanix** [comment]
Thanks for this.

I did actually create a fix for this but somehow forgot to merge the PR for the last release.

The issue will occur for the next release as well because of this - but will be solved after upgrading.
