### ISSUE TITLE
[Feature Request] Add Support for Multiple Connection Profiles

### ISSUE THREAD

**Issue by xInsertx** [Tympanix/Electorrent#31]
Can we have support for multiple connection profiles so we can toggle between servers.

This app is great, its the one of two real features i'd kill for.

**Comment by Tympanix** [comment]
I have actually been thinking about this idea myself. Great suggestion. I'll see what I can do

**Comment by xInsertx** [comment]
The easiest way to start with i believe would be having a single active profile that can be easily toggled to another via menu or drop down box.

Some considerations:

There will need to be a option for how to handle startup. This should be controlled by a option to either a) not connect to any profile, b) connect to last used, c) connect to profile marked default.

This will be important when handling magnet links / torrent filed passed by windows.

I haven't used Electron before but i might dig into the code and have a look.

**Comment by Tympanix** [comment]
This is exactly the problem I'm trying to solve. If you have any experience with JavaScript, AngularJS or web development please feel free to fork and have a look at the code :)
