### ISSUE TITLE
Electorrent integration with Transmission using Docker

### ISSUE THREAD

**Issue by Vishal-09-00** [tympanix/Electorrent#320]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [✔] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**
3.00
**Operating System:**
Linux
**Application Version:**
2.8.3
**Description:**
I am running Transmission as a docker container, can I integrate Electorrent with it?

**Comment by tympanix** [comment]
Electorrent supports connecting to the Transmission API and does not care if it is running in a container or not. In fact, the e2e tests for Transmission is provided by Transmission running in a docker container
