### ISSUE TITLE
refuses to accept a self-signed certificate for no reason

### ISSUE THREAD

**Issue by sthalik** [tympanix/Electorrent#331]
**Client:**
- [ ] µTorrent
- [x] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:**

qBittorrent v4.5.2

**Operating System:**

FreeBSD 13.2-RELEASE

**Application Version:**

Electorrent 2.8.3

**Description:**

A balloon pops up saying that the certificate is for a different host name. It can't be overridden and the common name is actually fine.

```console
subject=C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = 192.168.2.1
issuer=C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = 192.168.2.1
```

**Comment by tympanix** [comment]
Hi @sthalik.

The convention is to put the ipv4 addresses in the SAN of the certificate. Using the CN may work for some browsers, while Nodejs is more strict in their implementation.

**Comment by sthalik** [comment]
That did the trick. Thank you.
