### ISSUE TITLE
Project maintenance?

### ISSUE THREAD

**Issue by reedy** [tympanix/Electorrent#339]
Hello,

Checking in as it's been over a year since any commits to master, or similarly, any releases.

There's a handful of @dependabot PR's for dependancy bumps in various states, #279, #282, #298, #317, #319, #323, #324, #325, #327, #328, #330 - https://github.com/tympanix/Electorrent/pulls/app%2Fdependabot

And then CI is seemingly just broken on master anyway - #338

Thanks!

**Comment by tympanix** [comment]
Hi @reedy 

There's not much new feature development going on (life and so on). Maintenance is mostly kept to bug fixing and keeping the app compatible ever so often. This is usually a matter of updating the Electron framework, however, it hasn't been done in a while, as you pointed out.

I do accept PRs.
