### ISSUE TITLE
[Feature Request] Better Filtering Support for Labels / Trackers

### ISSUE THREAD

**Issue by xInsertx** [Tympanix/Electorrent#34]
Add support for filtering by Labels and/or Trackers to the left hand side.

**Comment by Tympanix** [comment]
This is not a feature I can implement for all clients due to incompatibility with the the APIs. Do you have a specific client in mind?

**Comment by xInsertx** [comment]
Well tracker filtering should be able to be done for any client. Labels should be on clients that support labels (ie: deluge rtorrent qbittorent). 

As a side note I would also hide the label row when using transmission as it's currently being displayed.

**Comment by Tympanix** [comment]
If the API does not cooperate I will not be able to implement filtering based on tracker. E.g. with qBittorrent ([see here](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-trackers)) there is no way of achieving this without making a HTTP call for every listed torrent. This is highly unpractical hence why the official web UI does not support this feature as well. uTorrent is simply out of the question as well.

If you can find (or know) any official or third party web UI that supports this feature, for any of the clients, please let me know. rTorrent is by now the only client API cooperating on this matter (i have inspected [ruTorrent](https://github.com/Novik/ruTorrent) for this implementation).

**Comment by Tympanix** [comment]
As of now this feature has been implemented for rTorrent and Transmission. It does not seem likely that it is trivial to implement on other clients.
