### ISSUE TITLE
Cannot scroll through and select labels at the bottom via "tag/label" icon

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#36]
I have a ton of labels in qBit. Sadly in Electorrent, I can't seem to scroll through and select the labels at the bottom since it exceeds the size of the window. Going fullscreen or Increasing my screen res might temporary solve this but I'd prefer not to.
Thanks.

**Comment by Tympanix** [comment]
I never thought about this. Thank you for pointing that out 🔢

**Comment by Tympanix** [comment]
I have done some testing now. I don't see this issue. When adding a lot of labels I can use the scrollbar in the left menu pane to scroll up and down. Please tell me if you see the scrollbar or otherwise elaborate on this issue :)

**Comment by valdotdev** [comment]
Oh I meant when clicking the tag icon on the top beside the "More" button. I could barely see my other labels on the bottom.

**Comment by Tympanix** [comment]
Of course. How silly of me. I will see what I can do :)

**Comment by Tympanix** [comment]
I have made a solution I think you'll quite like 👍

**Comment by valdotdev** [comment]
Thanks!

**Comment by Tympanix** [comment]
It is only text. I tend to add a __new label__ button in the next release :) Thank you for your feedback
