### ISSUE TITLE
OS X Doesn't Load Anything

### ISSUE THREAD

**Issue by kenetik** [Tympanix/Electorrent#4]
Latest OS X version doesn't display anything when trying to run/load it.

```
$ pwd; shasum -a 512 Electorrent
/Applications/Electorrent.app/Contents/MacOS
6052ec5a3cc598ed13bb5d4dc1210086d747d51288e8175301c05e286133f71c9d6a24320be6a04109b6c9eed736a2625d158687e6d316ec4afbd9d98d707585  Electorrent
```

OS X Version: 10.11.6 (15G31)

![screen shot 2016-08-26 at 8 37 35 am](https://cloud.githubusercontent.com/assets/3607606/18007313/24da4694-6b69-11e6-8419-faa1bfa58d83.png)

**Comment by Tympanix** [comment]
Can you please open the developer console under _"View"_ -> _"Toggle Developer Tools"_ and send me the information. I will look at it ASAP :+1:

**Comment by Tympanix** [comment]
Should be resolved in the latest 1.1.1 release (that is if you are using qBittorrent). Please get back to me and let me know

**Comment by kenetik** [comment]
Sorry I've just returned from the office. It was the latest build available and from checking, there is no Toggle Developer Tools option.

**Comment by Tympanix** [comment]
No problem. Also _cmd_+_alt_+_i_ should also do the trick. The problem was supposedly no http timeout when connecting to qBittorrent leaving it at the default 30 seconds. I've set this to 5 seconds i the new release and added a graphical spinner while connecting. Download the new version and test it out :+1:

**Comment by valdotdev** [comment]
Same thing for me. First time trying out this app. Using v1.1.1 on OSX 10.11.6

**Comment by Tympanix** [comment]
I will get right to it

**Comment by valdotdev** [comment]
Thanks! I'm guessing it only happens for people who installs it for the first time. So apparently versions above 1.0.2 won't work.

**Comment by Tympanix** [comment]
New version is compiling. Hang tight. Thanks for pointing out the bug :+1:

**Comment by valdotdev** [comment]
Works as expected! Thanks!
