### ISSUE TITLE
Re-arrange columns (v2 Beta.0)

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#40]
Trying out the v2 beta. I noticed you can't arrange the columns. At least not yet. :)

**Comment by Tympanix** [comment]
You can change them in settings by dragging. I will make this more clear graphically. I still know of some bugs which has to be fixed regarding columns before the release though. Thank you for giving feedback on the beta :)

**Comment by Tympanix** [comment]
I have released a new beta version with fixes. You are more than welcome to do some beta testing. Any bugs you find will help me towards the release of v2.0
