### ISSUE TITLE
qBittorrent Sequential Download

### ISSUE THREAD

**Issue by OctoOsmo** [Tympanix/Electorrent#44]
It would be nice to use this feathure by default fo qbittorrent or have a button to enable it.

**Comment by Tympanix** [comment]
I don't see this functionality in the qBittorrent settings. I do however see the action `Download in sequential order` in the context menu as a per torrent setting. I could add this to the context menu in Electorrent as well. Would this be sufficient?

[API documentation](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#toggle-sequential-download)

**Comment by OctoOsmo** [comment]
Yes, it would be wonderful.
