### ISSUE TITLE
rTorrent magnet links can't resolve tracker

### ISSUE THREAD

**Issue by brandom** [Tympanix/Electorrent#45]
I can connect to rTorrent v0.9.2 but when a torrent starts it immediately disconnects and cannot reconnect until the torrent is removed.

Electorrent v2.0.0.173

**Comment by Tympanix** [comment]
I have just tested this without any luck to reproduce the error. Can you elaborate with instructions on how to reproduce the error? I would also like to know:
* Did you add the torrent from Electorrent or from ruTorrent?
* Did you add the torrent by drag-and-drop / magnet link / browsing file system?
* Did you connect to a local machine or remote machine?
* By disconnected do you mean it freezes or shows the wall plug (disconnect) icon?

**Comment by brandom** [comment]
The torrent was added using a magnet link from Electorrent. The torrent begins downloading in rTorrent but the connection is immediately lost. It seems like as long as there is data to report to Electorrent it will not connect again. I have to remove the torrent and reopen Electorrent for it to connect.

The machine is remote and it shows the wall plug icon and says "Connection Lost!"

**Comment by brandom** [comment]
I would think it would be easy to reproduce unless it is specific to my rTorrent install. It could be the debian repo package. I can try installing the latest from source.

**Comment by brandom** [comment]
Same exact behavior when compiling from source using latest xml-rpc-c libtorrent and rTorrent. Perhaps it is my nginx config?

**Comment by Tympanix** [comment]
I have tracked down the error, it has to do with a new feature implemented in 2.0.0 which fetches the tracker for each torrent. I will get a fix out as soon as possible. I expect a resolution by tomorrow. Thank you for reporting 👍

**Comment by brandom** [comment]
Hah, just quit being lazy and cloned and debugged myself. Looks like the tracker was using udp and the regex didn't match causing an error at line 161.

**Comment by Tympanix** [comment]
Exactly. A PR is more than welcome :)

**Comment by Tympanix** [comment]
Otherwise I will get to it after work tomorrow

**Comment by Tympanix** [comment]
The bug has been fixed in v2.0.1. I ended up allowing the regex to accept [any protocol](https://github.com/Tympanix/Electorrent/blob/master/scripts/bittorrent/rtorrent/rtorrentservice.js#L5) and checked that the regex was [actually matching](https://github.com/Tympanix/Electorrent/blob/master/scripts/bittorrent/rtorrent/rtorrentservice.js#L163). Thanks again 👍
