### ISSUE TITLE
SSL/TLS connections not supported

### ISSUE THREAD

**Issue by phipolis** [Tympanix/Electorrent#47]
I'm coming from clients like Transmission-remote-gtk and Transdroid, where there is a "use ssl" checkbox in the connection settings. While the transmission-daemon doesn't itself support SSL/TLS, some people place a proxy in front of the daemon. (for example, [here](https://gist.github.com/michaelkeevildown/072b2f94af6bfa1416ee44c7004aff43) and [here](https://jay-baker.com/transmission-web-interface-reverse-proxy-with-ssl-using-nginx-on-arch-linux/)) It would be awesome if Electorrent supported using https connections.

**Comment by Tympanix** [comment]
Never though about that. The `http` url is hardcoded into the program. I could add an option to chose between `http` and `https` in the next release. Thank you for your suggestion 👍

**Comment by Tympanix** [comment]
a43eab27c009a15401a12e4b85eff7d7e3170ae9
