### ISSUE TITLE
Unable to connect to Tranmission server

### ISSUE THREAD

**Issue by dinowozo** [Tympanix/Electorrent#49]
I can access the webui by ip_adress:9091 and I know that is working but Electorrent just won't connect.

**Comment by Tympanix** [comment]
That sucks. Let me have a look at it. Could you please elaborate with the version of Transmission, Electorrent and your operating system. Also please note that `https` will not be available until the next release.

**Comment by dinowozo** [comment]
I'm not using https, Used windows 10 and it didn't connect as well as running it on Linux 
Transmission 2.92 (14714)

**Comment by Tympanix** [comment]
Clodes by #53
