### ISSUE TITLE
Add option to specify path for http rTorrent

### ISSUE THREAD

**Issue by tuplink** [Tympanix/Electorrent#50]
my setup does not use /RPC2     using /plugins/httprpc/action.php but i see no option to set this option

**Comment by Tympanix** [comment]
You are right. The program works with the standard set up for torrent as [seen here](https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC). It should be no problem to configure in your favourite web server. I will however think about this for next release.

**Comment by tuplink** [comment]
Where can I edit the code once it is installed?

**Comment by Tympanix** [comment]
If you're trying to set up the `/RPC2` endpoint then you should chose a web server (i prefer nginx) and follow [the guide](https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC) i linked before. If you're unfamiliar with nginx and how to configure it, a simple youtube video or google search will get you started.

Also remember to have
```
scgi_port = localhost:5000
```
in your `rtorrent.rc` configuration, as the guide mentions. Good luck 👍

**Comment by tuplink** [comment]
Agreed but rTorrent is not the public http server so /rpc2 is inacessable
to public.   I see in rtorrentservice.js is where rpc2 is set. I can
obviously change these but how do I go about it

**Comment by Tympanix** [comment]
If you want to change the code for your purpose you are more than welcome. You may fork the project and change the path for rtorrent [here](https://github.com/Tympanix/Electorrent/blob/master/scripts/bittorrent/rtorrent/rtorrentservice.js#L74). Remember to do `npm install` to install dependencies then run the program with `npm start`. When you have a working version you can create yourself a binary by running `npm dist`.

I hope this helps
