### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kongledyret** [Tympanix/Electorrent#51]
Hi!

Is it possible to connect to url like f.ex domain/rutorrent ? If not how to enable this?

**Comment by Tympanix** [comment]
This is a planned feature for the next release. The feature would have to satisfy #50 and #47 such that one could connect securely using SSL over WAN.

I can't put a deadline on the release. If this feature is indispensable for you, you might have a go at it yourself. I would be happy to receive a PR.

**Comment by Tympanix** [comment]
On a side note. Nothing would prohibit you from using a domain name in the `IP Address` field. The URI would however have to match the default path which is `/RPC2` for rTorrent - and SSL would not be an option.

**Comment by Kongledyret** [comment]
Ok. Are you available at skype or similar? Was wondering if you could assist with the things you mentioned above here in your latest comment.

**Comment by Tympanix** [comment]
I release the software for free but I don't do personal assistance. I will however gladly answer your questions such that they can be of use for everyone. The setup I mentioned above can be achieved by following [this guide](https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC), which will expose the rTorrent API at `/RPC2` which is what Electorrent expects. Then simply enter your IP (or domain) when setting up Electorrent.

If the guide is too technical you can find more explanatory guides on google.

Good luck 👍
