### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Kongledyret** [Tympanix/Electorrent#52]
Hi,
Do you have any build instructions to build from source

Thanks

**Comment by Tympanix** [comment]
I currently do not have one. To summarize the project is using [electron-builder](https://github.com/electron-userland/electron-builder) which should be installed globally with `npm i -g electron-builder`. Gulp should be installed globally as well. Also check out my [package.json](https://github.com/Tympanix/Electorrent/blob/master/package.json) file. You should be able to run `npm run dist` and it should build sucessfully - given the dependencies are installed.
