### ISSUE TITLE
Compatibility with Bittorrent?

### ISSUE THREAD

**Issue by Lyechee** [Tympanix/Electorrent#54]
Hello!
I'm looking for half an hour now to contact you Tympanix ^^.
I am actually using µtorrent but my community gave me the advice to use Bittorrent (less bugs, better speed, etc). Would it be possible to make Electorrent compatible with this software? 
Thank you,
Lyechee

**Comment by Tympanix** [comment]
Hi @Lyechee 
Glad you did. If BitTorrent has an API with documentation then it would be no problem. AFAIK the API should the same as in uTorrent which leads me to believe that this would already work (or at least with minor tweaks). I was however not able to find any concrete documentation on the subject.

**Comment by sarathkcm** [comment]
Bittorrent's Web UI is the same as µtorrent's. I am currently using Electorrent with both Bittorrent & µtorrent.

**Comment by Tympanix** [comment]
Thank your for clearing that up @sarathkcm. Closing
