### ISSUE TITLE
Reconnect seems broken

### ISSUE THREAD

**Issue by phipolis** [Tympanix/Electorrent#57]
I believe I see reconnect logic in the code, but after a connection interruption, 2.1.0 displays the "Connection Lost" overlay indefinitely until I reconnect manually. I'm not sure if there isn't actually functional reconnect, or perhaps it has to do with my using the new https connection feature.

**Comment by Tympanix** [comment]
It should be functional. I will make sure to fix this. Don't hesitate to report other bugs. Thank you 👍
