### ISSUE TITLE
Latest qBittorrent build breaks 3rd Party WebUI clients

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#58]
Apparently, there's a problem with the 3.3.13 update
I'm not entirely familiar with qBit's codebase  and haven't read the whole thing so I'll just link the issue here https://github.com/qbittorrent/qBittorrent/issues/6882
Just so you know :D

**Comment by Tympanix** [comment]
Thank you for linking this. There seems to be a lot of discussion on this topic. The problem may already have been fixed ([see here](https://github.com/qbittorrent/qBittorrent/pull/6887)) for future versions. If the problem persists in future versions I will definitely fix it. Lets see what happens in 3.3.14 and onwards.

**Comment by valdotdev** [comment]
Awesome! Thanks for the quick feedback.

**Comment by valdotdev** [comment]
@Tympanix 
It seems issue [6882](https://github.com/qbittorrent/qBittorrent/issues/6882) was closed and [6887](https://github.com/qbittorrent/qBittorrent/pull/6887) was merged for the qBit 3.3.14 release a few hours ago. But unfortunately Electorrent still won't connect.

**Comment by Tympanix** [comment]
Thanks for the heads up. I will try to update the client so everyone can use the latest version of qBittorrent. However, as of now, information on how to circumvent the CSFR protection is sparse, and I haven't been able to find any concrete information on it.
