### ISSUE TITLE
A few further issues with torrent view columns

### ISSUE THREAD

**Issue by phipolis** [Tympanix/Electorrent#67]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [x] Transmission
- [ ] rTorrent

**Client Version:** Transmission daemon 2.84 (14307)

**Operating System:** Linux 

**Application Version:**  2.1.4 AppImage

**Description:** 

A few more column issues I've observed:

- When adding a new torrent, it appears with "A few seconds ago" under Date Added. it does not update unless one reloads the view.
- Peers count displays in 2.1.0, but doesn't show anything in later versions
- Seeds count is always blank in all versions I have

Thank youuuuu for all you do! This has quickly become my favorite remote torrent client.

**Comment by Tympanix** [comment]
Glad to hear it :). Please keep issue reports coming if you find any other bugs. Even the little ones. This helps me out a lot. A patch will be released later today.
