### ISSUE TITLE
Can't connect with user & password

### ISSUE THREAD

**Issue by aropid** [Tympanix/Electorrent#69]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [x] rTorrent

**Client Version:**
rutorrent is v3.7 on ubuntu 14.04
**Operating System:**
windows 10
**Application Version:**
2.1.5
**Description:**
Using correct user/password i get the following error:
![image](https://user-images.githubusercontent.com/29828069/27767041-3587cf44-5e9c-11e7-9548-ef78e5aa2603.png)

I have tried 2 different boxes w/ rtorrent installed and i get the same error on both.

**Comment by Tympanix** [comment]
I have had little luck tracking down the problem you are experiencing. Have you set up your rTorrent following [this guide](https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC)? Are you sure the `/RPC200` is the correct endpoint? If this does not work you may also try to provide the direct path to the `action.php` script provided by ruTorrent. It is usually `/plugins/httprpc/action.php`.

If neither of the above works maybe you could supply me with more information. Are you using a seedbox provider or hosting your own? If you are using a seedbox provider maybe they have established their own authentication mechanism in front of ruTorrent, which is not basic authentication? Can you visit the above URL in the browser and have the basic authentication dialog show up? Alternatively try to change your password/username momentarily into something that only contains numbers and letters.

**Comment by aropid** [comment]
I am using a seedbox provider. I opened a ticket with them and was told /RPC200 was the correct endpoint. However, when i try to open it in browser i get a "500 Internal Server Error" and no authentication dialog shows up.

Action.php doesn't help, I also tried opening it in browser i just get a page that says "false"

I added `SCGIMount /RPC2 127.0.0.1:5000` to the end of `apache2.conf` and I could log in with Electorrent, but no torrents would show up and I get a connection lost error shortly after, if that's any help.

**Comment by Tympanix** [comment]
The response you with "false" you are getting from `action.php` is expected - which is good news. Concerning your apache configuration - are you sure your `rtorrent.rc` configuration is set up to listen on `127.0.0.1:5000`? If not, please check that your `rtorrent.rc` configuration contains `scgi_port = localhost:5000` as described in [the guide](https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC). Remember to restart rtorrent.

If you have further troubles you may need to manually check whether the endpoint is working or not. I suggest using a tool like [postman](https://www.getpostman.com/) for this. You can check whether your `/RPC2` endpoint works by posting the following XML snippet (remember your basic authentication and setting your request to `POST`):
```xml
<?xml version="1.0"?>
<methodCall>
   <methodName>system.client_version</methodName>
</methodCall>
```

You should get a response with the version of rtorrent (wrapped in XML). When you can successfully retrieve this response you know that your endpoint is working. You may also try this using `action.php` or your `/RPC200` endpoint. Please get back to me if you have any further troubles.

**Comment by Tympanix** [comment]
Closed due to inactivity
