### ISSUE TITLE
Sorting hides some entries

### ISSUE THREAD

**Issue by vmitchell85** [Tympanix/Electorrent#72]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [x] Transmission
- [ ] rTorrent

**Client Version:**
2.92 (14714)
**Operating System:**
MacOS 10.12.5
**Application Version:**
2.1.6 (2.1.6.224)
**Description:**
Sorting items makes a number of entries disappear. I also have configured specific columns and the resizing of those columns gets weird after the first one.

**Comment by vmitchell85** [comment]
Here is a video of the sorting issue: https://www.youtube.com/watch?v=zXs3kCGmaus

**Comment by Tympanix** [comment]
Thanks for reporting this bug. Can you tell if the columns disappearing
have something in common? Also using Ctrl+I (or Ctrl+Shift+I) will bring up
the developer console. Can you see any bugs when you sort?

**Comment by vmitchell85** [comment]
I couldn't determine the issue with the entries not displaying. But I think the concern with the column resizing may be due to it being unintuitive. When I drag between two columns I expect to be resizing the column on the left, and I think it's resizing the column on the right.

**Comment by Tympanix** [comment]
For the resizing of columns try changing the `Table Resize Style` to `Relative` and see if that feels more natural to you.

As for the entries not displaying I have found the problem. The list of torrents is automatically extended when you scroll to the bottom (as a way of incremental rendering). The starting limit for entries is 25 which is easily exceeded when using `Compact Listings` and having the application full-screen. When all 25 entries are displayed without scrollbars, the `infinite-scroll` will not be triggered.

I will work towards a solution in the coming days. Thanks for reporting the bug.

**Comment by vmitchell85** [comment]
Table resize style changes worked great!

I'll await a fix for the other issue.

Thanks!
