### ISSUE TITLE
No option to delete data when torrent is removed

### ISSUE THREAD

**Issue by austinfox** [Tympanix/Electorrent#74]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [x] rTorrent

**Client Version:**
3.7
**Operating System:**
MacOS Sierra 10.12.6
**Application Version:**
2.1.8
**Description:**
Removing a torrent does not remove the corresponding file/folder associated with the torrent. In the rTorrent webui, there is an option to 'remove and delete data'. Electorrent should expose this option or remove the data by default (assumes user has dealt with data - downloaded via ftp etc...)

**Comment by austinfox** [comment]
Based on this function from ruTorrent:
https://github.com/Novik/ruTorrent/blob/31a395ee6c9bc756d92c4c038ad229e1393ac1aa/plugins/erasedata/init.js#L41

It appears the only addition needed to add this functionality is a call to 'delete_tied' from the xmlrpc api before making the call to 'erase'. I'm not exactly sure what the first call to 'set_custom5' is doing, but I don't think this is necessary.

**Comment by Tympanix** [comment]
Thank you. I have been searching on documentation on how to achieve this myself. Feature will be added in the upcoming release.

**Comment by Tympanix** [comment]
For future references the `set_custom5` property is necessary for the deletion of files to work. Somehow, behind the scenes, rTorrent checks for this property upon deletion. A value of `1` mean normal deletion while `2` means force deletion.

**Comment by austinfox** [comment]
Amazing turnaround! Thanks for handling this - I would have eventually submitted a PR but it looks like it was easy for you as you already know the code base 😜. Does XMLRPC have better documentation somewhere? I had no idea what set_custom5 did, glad you figured it out though.

**Comment by Tympanix** [comment]
No in general there is not much documentation on rTorrent, which is a real shame. The links you provided are the ones I use myself. ruTorrent by Novik also has, according to me, a rather difficult code base to read. Ultimately I would also like the *set ratio group* and *set channel* option from rTorrent - but without documentation I am lost. If you come across any hints let me know.
