### ISSUE TITLE
Timeout Error when SSL cert is self-signed

### ISSUE THREAD

**Issue by http403** [Tympanix/Electorrent#80]
**Client:**
- [ ] µTorrent
- [x] qBittorrent
- [ ] Transmission
- [ ] rTorrent

**Client Version:**
3.3.7
**Operating System:**
Windows 10 Pro
**Application Version:**
2.1.10
**Description:**
Electorrent report time out error instead of a certificate error when a self-signed cert is used. It is difficult to debug when it provide such a misleading info. Please fix.

**Comment by Tympanix** [comment]
I will look into this issue once I have the time. I have a lot on my plate at the moment though. Thank you for reporting. This is definitely something that should be fixed.

**Comment by http403** [comment]
Currently, I solve it through add the self-signed cert to my MS certificate storage as trusted root, but it is super inconvenient and most of the general user don't know about this. I hope you can fix it by allowing self-signed certificate with a explicit warning, which is way much better. I know you have a lots of work going on so take your time.

**Comment by Tympanix** [comment]
There is a really nice way of handling self-signed certificates here:
https://electron.atom.io/docs/api/app/#event-certificate-error

This will provide what you mentioned above.

**Comment by http403** [comment]
Actually, I'm not a programmer. So I really don't know how to apply the patch.
