### ISSUE TITLE
Error when assigning a label

### ISSUE THREAD

**Issue by Lyechee** [Tympanix/Electorrent#82]
**Client:**
BitTorrent

**Client Version:**
7.10
**Operating System:**
W10 x64
**Application Version:**
2.1.10
**Description:**
To put the files in the right place, I use labels that put the file in the respective folders.
I declared my HTPC as a µTorrent source, and everything seems to work well. But when I try on ElecTorrent to assign a label to a file (already created so I can click on the name I chose on Bittorent) I get this error: "The action could not be performed because the server responded with a faulty reply."

Thanks in advance.
Regards,
Nicolas

**Comment by Tympanix** [comment]
Maybe the BitTorrent API is slightly different than that of µTorrent (although they should be similar). I will make sure to give this a look.

**Comment by Lyechee** [comment]
Thanks! If I can help, tell me.
Nicolas
