### ISSUE TITLE
[Feature Request] Synology DSM Download Station support

### ISSUE THREAD

**Issue by enchained** [tympanix/Electorrent#84]
Synology NASes are widely used and have Download Station as their default (and sometimes only) client. It's something like modified transmission, but its config file is hidden and resets on every launch, generating a new password: https://forum.synology.com/enu/viewtopic.php?t=34649

Is it possible to add Download Station support based on its official API instead? 

https://global.download.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf

https://github.com/kwent/syno/wiki/Download-Station-API
https://github.com/kwent/syno Node.js wrapper

**Comment by Tympanix** [comment]
This is definitely possible since the API has very good and thorough documentation. I can not promise support will come anytime soon - but your suggestion is duly noted. Thanks for reporting.

**Comment by Tympanix** [comment]
Assigned to @Paaff since a testing environment with a _Synology Download Station_ is required.

**Comment by Paaff** [comment]
I've taken a look at the documentation for the Synology Download Station API and it looks very promising. 

My schedule is pretty busy these days, but I will try to sqeeze this in 👍 .
