### ISSUE TITLE
Unable to connect to qBittorrent v3.1.10 - invalid username/password

### ISSUE THREAD

**Issue by TimvdEijnden** [Tympanix/Electorrent#85]
**Client:**
- qBittorrent

**Client Version:**
qBittorrent v3.1.10

**Operating System:**
MacOS 10.12.6

**Application Version:**
Electorrent: Versie 2.1.10 (2.1.10.236)

**Description:**
Cannot connect to qBittorrent on dietPI, webinterface works correctly on HTTP port 1340.
Gives the `incorrect username/password` error while the entered username and password are correct. You can try it with a default dietPI setup.

**Comment by Tympanix** [comment]
I would suggest you start out by updating qBittorrent to a newer version, something like v3.3.14, and try again. Testing out DietPI is quite cumbersome for me. Thanks for reporting.

**Comment by coreinsane** [comment]
I also have this problem.
I have an Orange Pi One with the latest armbian.
I have qbittorrent-nox as a headless torrent server. 
Which is by latest qBittorrent v3.1.10 (Web UI).
Followed this wiki to install it: https://github.com/qbittorrent/qBittorrent/wiki/Setting-up-qBittorrent-on-Ubuntu-server-as-daemon-with-Web-interface-(15.04-and-newer)

I am trying to connect with Electorrent under Windows 10.
When i am using the built in qbittorrent webui through 8080 port, it works, but Electorrent shows Unable to connect to qBittorrent - invalid username/password.
Hope this helps

**Comment by Tympanix** [comment]
Good with more case in points. So you say it works, but it says `invalid username/password`? Is it simply a case of a false negative? And can you explain to me what `qbittorrent-nox` is? Since you are also using v3.1.10 I am still thinking it is a problem with the older webUI.

**Comment by Tympanix** [comment]
I have now installed qBittorrent v3.1.10 and confirmed that this is the reason for the error. Also in the qBittorrent documentation says:

*The WebUI API has been overhauled in qBittorrent v3.2.0* [link](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation-(qBittorrent-v3.1.x))

**Comment by Tympanix** [comment]
I have determined that supporting the older v3.1.10 API is not going to be realistic. I would suggest you update instead. If enough people would _really_ like to support the older API maybe I'll reconsider. I will be implementing a correct response when trying to connect to deprecated versions of qBittorrent.

**Comment by coreinsane** [comment]
How to update? The latest qbittorrent-nox is 3.1.10 am I correct?

**Comment by Tympanix** [comment]
If your package manager does not have an updated version, I would suggest you compile qBittorrent yourself using `./configure --disable-gui` to disable the GUI. As I understand the `nox` in `qbittorrent-nox` simply means no X server (or no GUI). You can read more [here](https://github.com/qbittorrent/qBittorrent/wiki/Running-qBittorrent-without-X-server)

**Comment by TimvdEijnden** [comment]
I've upgraded to 3.3.x using this guide: https://github.com/qbittorrent/qBittorrent/wiki/Compiling-qBittorrent-on-Raspbian-for-LeMaker-Banana-Pro 

except I downloaded the qbittorrent source tar.gz instead of cloning the GitHub repo. Now it works! 😃

**Comment by coreinsane** [comment]
I have switched my pi project from debian jessie server to ubuntu xenial server.  
And so far so good, and also no more incorrect username/password, because xenial packs 3.3.x qbittorrent packages :)

**Comment by Tympanix** [comment]
Glad it worked out 👍
