### ISSUE TITLE
What is qBittorrent sequential download?

### ISSUE THREAD

**Issue by coreinsane** [Tympanix/Electorrent#88]
Start a new thread about General Q & A about this project.

**Comment by coreinsane** [comment]
There is an option to sequential download torrents.
In qBittorrent side, is it implemented to just sequentially download the torrent, or to download first and last pieces First as well?

**Comment by Tympanix** [comment]
@coreinsane The _sequential download_ option is not directly implemented in Electorrent. It simply exposes the functionality from qBittorrent through it's API, so it is completely identical to the _sequential download_ button in the qBittorrent GUI. Therefore you will have to read the qBittorent documentation on what it does, but off the bat, I would assume it downloads the pieces in sequential order from start to finish which means the last piece will be downloaded last.

**Comment by Tympanix** [comment]
I would also suggest you create a new issue for whatever question you might have, such that it is searchable in the issues page. Having them in a long thread is not convenient.

I wish you would use the issues to contact me (it benefits everyone). But if you insist on writing me an email my email address should not be too hard to find in the commit history. I will not be providing it here to encourage people to use the open forum instead.
