### ISSUE TITLE
Add torrents via URL and local file, not just magnet links

### ISSUE THREAD

**Issue by valdotdev** [Tympanix/Electorrent#9]
First off, thanks for your hard work and sorry for bombarding you with requests right off the bat. But here's another one from me. :)

The ability to add torrent files via URL and torrent files located in your local machine. I'm using qBittorrent primarily.

**Comment by Tympanix** [comment]
Thank you very much valdotdev.

All of your suggestions are good. In fact these are some of the things that I've been delaying to get an early version out. I will put all these issues to attention in the next major release :+1:

**Comment by valdotdev** [comment]
Many thanks!

**Comment by Tympanix** [comment]
Version 1.2.0 has been released with all the features you suggested. It is public for download right now. Please get back to me if you can think of anything else that would improve the user experience of the application. Thank you.

**Comment by valdotdev** [comment]
Thanks! Will do!

**Comment by Tympanix** [comment]
You are correct. This was implemented in 6ceb176 and only handles the _magnet://_ protocol. I have created a new issue #17 which will improve on this matter.

**Comment by valdotdev** [comment]
Thanks a lot!
