### ISSUE TITLE
No support for authType digest

### ISSUE THREAD

**Issue by rb28z2** [tympanix/Electorrent#97]
**Client:**
- [ ] µTorrent
- [ ] qBittorrent
- [ ] Transmission
- [x] rTorrent

**Client Version: rtorrent 0.9.6, rutorrent v3.7**

**Operating System: Windows 10 1709 (Build 16299.192)**

**Application Version: 2.1.11**

**Description:**

My rutorrent setup is secured using `authType digest` using Apache and I was getting an invalid user/pass error when trying to setup Electorrent for the first time.

I ended up changing the authentication method to `authType basic` and I was able to login and use the program as expected.

My request is to add `digest` support for authentication if possible.

**Comment by tympanix** [comment]
Very valid point. This could be implemented using a `md5` hashing implementation [(like this one)](https://github.com/blueimp/JavaScript-MD5). This is not top priority but I may get to it eventually. Thanks for reporting.
